version: "3.8"

services:
   jenkins-srv:
    build: .           
#   image: kayy256/jenkins-srv:latest
    container_name: jenkins-srv
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2223:22"
    volumes:
      - ./jenkins_workdir:/var/jenkins_home
      - ./jenkins_update/jenkins:/usr/share/jenkins
      - ./ssh-keys/.ssh:/var/jenkins_home/.ssh

#    networks:
#      - jenkins-srv_network 
            
#networks:
#    jenkins-srv_network:
#             driver: bridge
